// src/pages/FieldDetail.tsx
import { useParams } from '@solidjs/router'
import { differenceInCalendarDays, startOfDay } from 'date-fns'
import {
  Component,
  createEffect,
  createSignal,
  Show,
  useContext,
} from 'solid-js'
import { AuthenticationContext } from '../components/AuthenticationProvider'
import { ConfirmPaint } from '../components/ConfirmPaint'
import { DaysLeftChip } from '../components/DaysLeftChip'
import { ErrorPrompt } from '../components/ErrorPrompt'
import { Field } from '../components/Field'
import { FieldsContext } from '../components/FieldsProvider'
import { Header } from '../components/Header'
import { OnlineContext } from '../components/OnlineStatusProvider'
import { Page } from '../components/Page'
import { StatusLabel } from '../components/StatusLabel'
import { SupabaseContext } from '../components/SupabaseProvider'
import { SIZES } from '../utilities/constants'
import { getFieldWithAdjustedRainFactorAndDryDays } from '../utilities/predictNextPainting'
import { Field as FieldType, FieldSize } from '../utilities/types'
import { formatDate } from '../utilities/utils'
import styles from './FieldDetail.module.css'

export const FieldDetail: Component = () => {
  const { supabase } = useContext(SupabaseContext)
  const [fieldId, setFieldId] = createSignal(useParams().id)
  const [thisField, setThisField] = createSignal<FieldType>()
  const [saveError, setSaveError] = createSignal<string>()
  const [showConfirmPaint, setShowConfirmPaint] = createSignal(false)
  const isOnline = useContext(OnlineContext)
  const { user } = useContext(AuthenticationContext)
  const { fields, saveField, fetchFields } = useContext(FieldsContext)

  // Reload fields when this page loads
  fetchFields()

  createEffect(() => {
    setThisField(fields()?.find((field: FieldType) => field.id === fieldId()))
  }, [fields])

  const paintField = async ({
    shouldAdjustFactor,
  }: { shouldAdjustFactor?: boolean } = {}) => {
    if (!thisField()) return
    setShowConfirmPaint(false)

    let fieldToSave = thisField()!
    if (shouldAdjustFactor) {
      fieldToSave = getFieldWithAdjustedRainFactorAndDryDays({
        currentField: fieldToSave,
        // Right now we assume it's unplayable on the date you painted:
        markUnplayableOn: startOfDay(new Date()),
      })
    }
    fieldToSave.lastPainted = startOfDay(new Date())

    console.log('Saving field ', fieldToSave)

    await saveField({ field: fieldToSave })
  }

  return (
    <Page>
      {/* Header children won't update unless there's some static text... odd? */}
      <Header backLocation="/fields" editFieldId={thisField()?.id}>
        {thisField()?.name}
      </Header>
      <ErrorPrompt error={saveError} />
      <Show when={thisField()} fallback={<div>Loading...</div>}>
        <div class={styles.DetailContainer}>
          <div class={styles.TitleRow}>
            <h1>{thisField()?.name}</h1>
            <div>
              <StatusLabel field={thisField} />
            </div>
          </div>
          <ul class={styles.List}>
            <li>
              <strong>Last painted:</strong>
              {formatDate(thisField()?.lastPainted)}
            </li>
            <li>
              <strong>Predicted next painting:</strong>
              {formatDate(thisField()?.predictedNextPaint)}
              <DaysLeftChip
                predictedNextPaint={thisField()?.predictedNextPaint}
                lastPainted={thisField()?.lastPainted}
              />
            </li>
            <li>
              <strong>Size:</strong>
              {thisField()?.size} (
              {thisField()?.customLength ??
                SIZES[thisField()?.size ?? FieldSize.full]
                  ?.recommendedMaxLength}
              L x{' '}
              {thisField()?.customWidth ??
                SIZES[thisField()?.size ?? FieldSize.full]?.recommendedMaxWidth}
              W)
            </li>
            <li>
              <strong>Description:</strong>
              {thisField()?.description}
            </li>
            <li>
              <strong>Group:</strong>
              {thisField()?.group}
            </li>
          </ul>
          <details>
            <summary>Details</summary>
            <div class={styles.DetailContainer}>
              <ul>
                <li>
                  <strong>Max dry days:</strong>&nbsp;{thisField()?.maxDryDays}
                </li>
                <li>
                  <strong>Rainfall days:</strong>&nbsp;
                  {thisField()?.rainfallDays}
                </li>
                <li>
                  <strong>Rainfall factor:</strong>&nbsp;
                  {thisField()?.rainfallFactor}
                </li>
              </ul>
              <Field
                fieldSize={() => thisField()?.size as FieldSize}
                customLength={() => thisField()?.customLength}
                customWidth={() => thisField()?.customWidth}
              />
            </div>
          </details>
          <div>
            <button
              onClick={() => setShowConfirmPaint(true)}
              disabled={
                !isOnline?.() ||
                differenceInCalendarDays(
                  new Date(),
                  thisField()?.lastPainted ?? new Date(),
                ) < 3
              }
            >
              Mark Painted
            </button>

            {/* <Show when={getIsFieldPlayable(field())}>
              <a role="button" class="contrast">
                Mark Unplayable
              </a>
            </Show> */}
            {/* <a role="button" class="secondary">
              Archive
            </a> */}
          </div>
          <ConfirmPaint
            show={showConfirmPaint}
            daysRemaining={() =>
              differenceInCalendarDays(
                thisField()?.predictedNextPaint ?? new Date(),
                new Date(),
              )
            }
            onPaint={paintField}
            onCancel={() => setShowConfirmPaint(false)}
          />
        </div>
      </Show>
    </Page>
  )
}

// src/pages/FIeldDetail.tsx
import {
  IonBackButton,
  IonButton,
  IonButtons,
  IonContent,
  IonFooter,
  IonHeader,
  IonItem,
  IonLabel,
  IonNote,
  IonPage,
  IonSkeletonText,
  IonTitle,
  IonToolbar,
  useIonViewWillEnter,
} from '@ionic/react'
import { differenceInCalendarDays } from 'date-fns'
import React, { useState } from 'react'
import { useParams } from 'react-router'
import { ConfirmPaint } from '../components/ConfirmPaint'
import { FieldSketch } from '../components/FieldSketch'
import { StatusLabel } from '../components/StatusLabel'
import { useSupabase } from '../components/SupabaseProvider'
import { paintField } from '../utilities/actions'
import { SIZES } from '../utilities/constants'
import { getField, getPaintHistory } from '../utilities/data'
import { getFieldWithAdjustedRainFactorAndDryDays } from '../utilities/predictNextPainting'
import { Field, FieldSize } from '../utilities/types'
import './FieldDetail.css'

export const FieldDetail = () => {
  const isOnline = true
  const [loading, setLoading] = useState(false)
  const [showConfirmPaint, setShowConfirmPaint] = useState(false)
  const [field, setField] = useState<Field>()
  const params = useParams<{ id: string }>()
  const { supabase } = useSupabase()

  useIonViewWillEnter(() => {
    getField({ supabase, id: params.id }).then((foundField) => {
      setField(foundField)
    })
  })

  const onPaint = async ({ adjustFactor }: { adjustFactor: boolean }) => {
    if (!field) return
    const resultingField = await paintField({ field, adjustFactor, supabase })
    setField(resultingField)
  }

  return (
    <IonPage id="field-detail-page">
      <IonHeader translucent>
        <IonToolbar>
          <IonButtons slot="start">
            <IonBackButton text="Fields" defaultHref="/fields"></IonBackButton>
          </IonButtons>
          {!loading && field && <IonTitle>{field.name}</IonTitle>}
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen>
        {loading ? (
          <FieldDetailSkeleton />
        ) : (
          <>
            {field ? (
              <>
                <IonHeader collapse="condense">
                  <IonToolbar>
                    <IonTitle size="large">{field.name}</IonTitle>
                  </IonToolbar>
                </IonHeader>
                <div className="ion-padding col gap-4">
                  <IonItem lines="none" style={{ alignItems: 'start' }}>
                    <IonLabel>
                      <IonNote>{field.description}</IonNote>
                    </IonLabel>
                    <IonLabel slot="end">
                      <StatusLabel field={field} />
                    </IonLabel>
                  </IonItem>

                  <table aria-description="Field information">
                    <tbody>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Predicted
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.predictedNextPaint?.toLocaleDateString()} (
                            {differenceInCalendarDays(
                              new Date(field.predictedNextPaint ?? new Date()),
                              new Date(),
                            )}
                            )
                          </IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Last painted
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.lastPainted.toLocaleDateString()}
                          </IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Size
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.size} (
                            {field.customLength ??
                              SIZES[field.size ?? FieldSize.full]
                                ?.recommendedMaxLength}
                            L x{' '}
                            {field.customWidth ??
                              SIZES[field.size ?? FieldSize.full]
                                ?.recommendedMaxWidth}
                            W)
                          </IonLabel>
                        </td>
                      </tr>
                      {!!field.group && (
                        <tr>
                          <td>
                            <IonLabel style={{ fontWeight: 'bold' }}>
                              Group
                            </IonLabel>
                          </td>
                          <td>
                            <IonLabel slot="end">{field.group}</IonLabel>
                          </td>
                        </tr>
                      )}
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Max dry days
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.maxDryDays} days
                          </IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Rainfall days
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.rainfallDays} days
                          </IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Rainfall factor
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {Math.floor((field.rainfallFactor ?? 0) * 1000) /
                              1000}
                          </IonLabel>
                        </td>
                      </tr>
                    </tbody>
                  </table>

                  <FieldSketch
                    fieldSize={field.size as FieldSize}
                    customLength={field.customLength}
                    customWidth={field.customWidth}
                  />
                </div>
              </>
            ) : (
              <div>Field not found</div>
            )}
          </>
        )}
      </IonContent>
      <IonFooter translucent collapse="fade">
        <IonToolbar>
          <IonButton
            slot="primary"
            onClick={() => setShowConfirmPaint(true)}
            fill={
              differenceInCalendarDays(
                new Date(),
                field?.lastPainted ?? new Date(),
              ) < 3
                ? 'outline'
                : 'solid'
            }
            disabled={
              differenceInCalendarDays(
                new Date(),
                field?.lastPainted ?? new Date(),
              ) < 3
            }
          >
            Mark Painted
          </IonButton>
        </IonToolbar>
      </IonFooter>
      <ConfirmPaint
        show={showConfirmPaint}
        daysRemaining={differenceInCalendarDays(
          new Date(field?.predictedNextPaint ?? new Date()),
          new Date(),
        )}
        onPaint={onPaint}
        reasonableLimitOfOverdueDays={(field?.maxDryDays || 12) * 2}
        onCancel={() => setShowConfirmPaint(false)}
      />
    </IonPage>
  )
}

const FieldDetailSkeleton = () => {
  return <IonSkeletonText animated={true} style={{ width: 80 }} />
}
