// src/components/FieldDetail.tsx
import { useParams, useNavigate } from '@solidjs/router'
import {
  Component,
  Show,
  createResource,
  createSignal,
  useContext,
} from 'solid-js'
import { SIZES } from '../utilities/constants'
import { FieldSize } from '../utilities/types'
import {
  formatDate,
  getPredictedDaysUntilPaint,
  getPredictedNextPaintDate,
} from '../utilities/utils'
import { ErrorPrompt } from './ErrorPrompt'
import styles from './FieldDetail.module.css'
import { getField, saveField } from './FieldStore'
import { Header } from './Header'
import { OnlineContext, OnlineStatus } from './OnlineStatusProvider'
import { StatusLabel } from './StatusLabel'

export const FieldDetail: Component = () => {
  const [fieldId, setFieldId] = createSignal(useParams().id)
  const [field, { refetch, mutate }] = createResource(fieldId, getField)
  const [saveError, setSaveError] = createSignal<string>()
  const isOnline = useContext(OnlineContext)
  const navigate = useNavigate()

  const paintField = async () => {
    if (!field) return

    try {
      const savedField = await saveField({
        ...field(),
        lastPainted: new Date(),
      })
      mutate(savedField)
    } catch (err) {
      console.error(err)
      setSaveError((err as Error).message)
    }
  }

  const setPlayable = (playable: boolean) => {
    // TODO playable will just extend the "base days" or "rain factor" by 1
  }

  return (
    <>
      <ion-header>
        <ion-toolbar>
          <ion-buttons slot="start">
            <ion-back-button
              text="List"
              onClick={() => navigate('/fields', { replace: true })}
            ></ion-back-button>
          </ion-buttons>
          <ion-title>
            <Show when={!field.loading}>{field()?.name}</Show>
          </ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content class="ion-padding">
        <ErrorPrompt error={saveError} />
        <Show when={!field.loading} fallback={<div>Loading...</div>}>
          <h1>{field()?.name}</h1>
          <ul class="none">
            <li>
              <div class={styles.StatusRow}>
                <StatusLabel field={field} />
              </div>
            </li>
            <li>
              <strong>Last painted:</strong> {formatDate(field()?.lastPainted)}
            </li>
            <li>
              <strong>Predicted next painting:</strong>{' '}
              {formatDate(getPredictedNextPaintDate(field()))} (
              {getPredictedDaysUntilPaint(field())} days)
            </li>
            <li>
              <strong>Max dry days:</strong> {field()?.maxDryDays}
            </li>
            <li>
              <strong>Rainfall days:</strong> {field()?.rainfallDays}
            </li>
            <li>
              <strong>Rainfall factor:</strong> {field()?.rainfallFactor}
            </li>
            <li>
              <strong>Size:</strong> {field()?.size} (
              {field()?.customLength ??
                SIZES[field()?.size ?? FieldSize.full]?.recommendedMaxLength}
              L x{' '}
              {field()?.customWidth ??
                SIZES[field()?.size ?? FieldSize.full]?.recommendedMaxWidth}
              W)
            </li>
            <li>
              <strong>Location:</strong> {field()?.description}
            </li>
          </ul>
          <div>
            <button onClick={paintField} disabled={!isOnline?.()}>
              Mark Painted
            </button>
            {/* <Show when={getIsFieldPlayable(field())}>
              <a role="button" class="contrast">
                Mark Unplayable
              </a>
            </Show> */}
            {/* <a role="button" class="secondary">
              Archive
            </a> */}
            <OnlineStatus />
          </div>
        </Show>
      </ion-content>
    </>
  )
}

// src/pages/FIeldDetail.tsx
import {
  IonAlert,
  IonBackButton,
  IonButton,
  IonButtons,
  IonContent,
  IonFooter,
  IonHeader,
  IonItem,
  IonLabel,
  IonList,
  IonNote,
  IonPage,
  IonSkeletonText,
  IonTitle,
  IonToolbar,
  useIonViewWillEnter,
} from '@ionic/react'
import React, { useState } from 'react'
import { useParams } from 'react-router'
import { ConfirmPaint } from '../components/ConfirmPaint'
import { getField } from '../data/fields'
import { SIZES } from '../utilities/constants'
import { Field, FieldSize } from '../utilities/types'
import './FieldDetail.css'
import { FieldSketch } from '../components/FieldSketch'

export const FieldDetail = () => {
  const isOnline = true
  const [loading, setLoading] = useState(false)
  const [showConfirmPaint, setShowConfirmPaint] = useState(false)
  const [field, setField] = useState<Field>()
  const params = useParams<{ id: string }>()

  useIonViewWillEnter(() => {
    getField(params.id).then((foundField) => {
      setField(foundField)
    })
  })

  return (
    <IonPage id="field-detail-page">
      <IonHeader translucent>
        <IonToolbar>
          <IonButtons slot="start">
            <IonBackButton text="Fields" defaultHref="/fields"></IonBackButton>
          </IonButtons>
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen>
        {loading ? (
          <FieldDetailSkeleton />
        ) : (
          <>
            {field ? (
              <>
                <div className="ion-padding col gap-4">
                  <IonItem lines="none" style={{ alignItems: 'start' }}>
                    <IonLabel>
                      <h1>{field.name}</h1>
                      <IonNote>{field.description}</IonNote>
                    </IonLabel>
                    <IonLabel slot="end">
                      Status
                      {/*<StatusLabel field={thisField} />*/}
                    </IonLabel>
                  </IonItem>

                  <table aria-description="Field information">
                    <tbody>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Last painted
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.lastPainted.toLocaleDateString()}
                          </IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Predicted
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            10
                            {/*{field.predictedNextPaint?.toLocaleDateString()}*/}
                          </IonLabel>
                          {/*<DaysLeftChip*/}
                          {/*  predictedNextPaint={field.predictedNextPaint}*/}
                          {/*  lastPainted={field.lastPainted}*/}
                          {/*/>*/}
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Size
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {field.size} (
                            {field.customLength ??
                              SIZES[field.size ?? FieldSize.full]
                                ?.recommendedMaxLength}
                            L x{' '}
                            {field.customWidth ??
                              SIZES[field.size ?? FieldSize.full]
                                ?.recommendedMaxWidth}
                            W)
                          </IonLabel>
                        </td>
                      </tr>
                      {!!field.group && (
                        <tr>
                          <td>
                            <IonLabel style={{ fontWeight: 'bold' }}>
                              Group
                            </IonLabel>
                          </td>
                          <td>
                            <IonLabel slot="end">{field.group}</IonLabel>
                          </td>
                        </tr>
                      )}
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Max dry days
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">{field.maxDryDays}</IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Rainfall days
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">{field.rainfallDays}</IonLabel>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <IonLabel style={{ fontWeight: 'bold' }}>
                            Rainfall factor
                          </IonLabel>
                        </td>
                        <td>
                          <IonLabel slot="end">
                            {Math.floor((field.rainfallFactor ?? 0) * 1000) /
                              1000}
                          </IonLabel>
                        </td>
                      </tr>
                    </tbody>
                  </table>

                  <FieldSketch
                    fieldSize={field.size as FieldSize}
                    customLength={field.customLength}
                    customWidth={field.customWidth}
                  />
                </div>
              </>
            ) : (
              <div>Field not found</div>
            )}
          </>
        )}
      </IonContent>
      <IonFooter collapse="fade">
        <IonToolbar>
          <IonButton
            slot="primary"
            onClick={() => setShowConfirmPaint(true)}
            // disabled={
            //   !isOnline ||
            //   differenceInCalendarDays(
            //     new Date(),
            //     field.lastPainted ?? new Date(),
            //   ) < 3
            // }
          >
            Mark Painted
          </IonButton>
        </IonToolbar>
      </IonFooter>
      <ConfirmPaint
        show={showConfirmPaint}
        daysRemaining={10}
        onPaint={() => {}}
        reasonableLimitOfOverdueDays={10}
        onCancel={() => setShowConfirmPaint(false)}
      />
    </IonPage>
  )
}

const FieldDetailSkeleton = () => {
  return <IonSkeletonText animated={true} style={{ width: 80 }} />
}
