// src-solid-fail/providers/SupabaseProvider.tsx
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { createContext, JSX } from 'solid-js'

const getSupabase = () => {
  return createClient(
    import.meta.env.VITE_PUBLIC_SUPABASE_URL,
    import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY,
  )
}

type SupabaseProvider = {
  children: JSX.Element
}

export const SupabaseContext = createContext<{
  supabase: SupabaseClient<any, 'public', any>
  resetSupabase: () => SupabaseClient<any, 'public', any>
}>()
export const SupabaseProvider = (props: SupabaseProvider) => {
  // When this is first added to the stack, just set the supabase variable
  let supabase = getSupabase()

  const resetSupabase = () => {
    supabase = getSupabase()
    return supabase
  }

  return (
    <SupabaseContext.Provider value={{ supabase, resetSupabase }}>
      {props.children}
    </SupabaseContext.Provider>
  )
}

// app/providers/SupabaseProvider.tsx
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import {
  createContext,
  FC,
  PropsWithChildren,
  useContext,
  useEffect,
  useState,
} from 'react'

type SupabaseProvider =
  | SupabaseClient<Record<string, any>, 'public', any>
  | undefined

const SupabaseContext = createContext<SupabaseProvider>(undefined as any)

export const SupabaseProvider: FC<PropsWithChildren> = ({ children }) => {
  const [supabase, setSupabase] = useState<SupabaseClient<any, 'public', any>>()

  useEffect(() => {
    if (!window.ENV.SUPABASE_URL || !window.ENV.SUPABASE_ANON_KEY) return

    setSupabase(
      createClient(window.ENV.SUPABASE_URL, window.ENV.SUPABASE_ANON_KEY),
    )
  }, [])

  if (!supabase) {
    return <div>Loading Supabase...</div>
  }

  return (
    <SupabaseContext.Provider value={supabase}>
      {children}
    </SupabaseContext.Provider>
  )
}

export function useSupabase() {
  const supabase = useContext(SupabaseContext)

  if (!supabase) {
    throw new Error('useSupabase must be used within a SupabaseProvider')
  }

  return supabase
}
